# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 04:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160409_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Asset_Value',
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
