# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160409_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='AssetValue',
            field=models.FloatField(default=100000000),
        ),
    ]
