# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_group_assetvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='AssetValue',
        ),
    ]
