# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_group_assetvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockName', models.CharField(max_length=100)),
                ('StockValue', models.FloatField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='Buy_At_Price',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
    ]
