# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160423_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='StockValue',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='CurrentPrice',
        ),
        migrations.AddField(
            model_name='stock',
            name='Time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 23, 7, 3, 59, 959593, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
