# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160423_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='Time',
        ),
    ]
