# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20160423_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='StockName',
        ),
    ]
