# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_stock_stockname'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(auto_now=True, default=datetime.datetime(2016, 4, 25, 17, 0, 15, 605659, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
