# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_transaction_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='time',
        ),
    ]
